'use client';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { AuthContextProvider } from '../context/AuthContext';
import { ThemeProvider } from 'next-themes';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <AuthContextProvider>
            <div className="w-full h-full bg-background-lm dark:bg-background-dm  text-text-lm dark:text-text-dm text-base">
              {children}
            </div>
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
